import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

def visualizeResult(x, y, x_lable, y_lable, figure_title):
	'''This function is provided for visualizing the result using the functions in the matplotlib package.'''
	'''Parameters:
	@x: array
	@y: array
	@x_lable: string. It's a label you will use for x axis.
	@y_lable: string. It's a label you will use for y axis.
	@figure_title: string. The title/name of the figure.

	Output:
	The picture generated by the matplotlib will be saved in your current directory.
	'''
	plt.plot(x, y)
	plt.title(figure_title)
	plt.xlabel(x_lable)
	plt.ylabel(y_lable)
	plt.savefig(figure_title+".png")